const PRODUCTS = [
  {
    name: 'NT1 - Yến Thô 100g',
    categoryId: '619f7d7c07a967f6eda06295',
    featuredImage: '/images/products/1.jpg',
    description: 'Được lựa chọn ngay từ khâu thu hoạch , chọn ra những tổ tròn điều, ít lông, đảm bảo độ trắng sáng, sạch ko bụi, đảm bảo trọng lượng khoảng 10g/tổ.',
    maxQuantity: 100,
    ratingAvg: 0,
    totalRatings: 0,
    regularPrice: 2400000,
    salePrice: 0,
    ingredient: '100% Yến sào (trắng)',
    mass: '100g',
    uses: 'Tổ yến chứa tới 18 loại acid amin mà cơ thể không tự tổng hợp được, cùng rất nhiều cacbonhydrat, muối khoáng, khoáng chất vi lượng.... giúp cơ thể khỏe mạnh, trẻ hóa tế bào, da trắng mịn, hồng hào và cải thiện trí nhớ.',
    preservation: 'Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp',
    expiryDate: '02 năm kể từ ngày sản xuất',
    origin: 'Việt Nam',
    currency: 'VND',
    ownerId: '619f7ec78a3dec0df2362c8f'
  },
  {
    name: 'NT2 - Yến Thô 50g',
    categoryId: '619f7d7c07a967f6eda06295',
    featuredImage: '/images/products/2.jpg',
    description: 'Được lựa chọn ngay từ khâu thu hoạch , chọn ra những tổ tròn điều, ít lông, đảm bảo độ trắng sáng, sạch ko bụi, đảm bảo trọng lượng khoảng 10g/tổ.',
    maxQuantity: 100,
    ratingAvg: 0,
    totalRatings: 0,
    regularPrice: 1200000,
    salePrice: 0,
    ingredient: '100% Yến sào (trắng)',
    mass: '50g',
    uses: 'Tổ yến chứa tới 18 loại acid amin mà cơ thể không tự tổng hợp được, cùng rất nhiều cacbonhydrat, muối khoáng, khoáng chất vi lượng.... giúp cơ thể khỏe mạnh, trẻ hóa tế bào, da trắng mịn, hồng hào và cải thiện trí nhớ.',
    preservation: 'Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp',
    expiryDate: '02 năm kể từ ngày sản xuất',
    origin: 'Việt Nam',
    currency: 'VND',
    ownerId: '619f7ec78a3dec0df2362c8f'
  },
  {
    name: 'HH11 - Yến sào thành phẩm xếp hoa hồng 100g',
    categoryId: '619f7d7c07a967f6eda06295',
    featuredImage: '/images/products/3.jpg',
    description: 'Được làm từ yến nguyên tổ mới khai thác được đem trực tiếp đến phòng sơ chế. Tổ yến sẽ được sơ chế rửa bằng nước sạch được lọc qua hệ thống RO, loại bỏ sạch hoàn toàn lông và bụi bẩn hoàn toàn thủ công, sấy khô có hình dạng xếp sợi theo định hình hoa hồng, cánh hoa hồng có nhiều sợi yến dài đắp bên ngoài bề mặt.',
    maxQuantity: 100,
    ratingAvg: 0,
    totalRatings: 0,
    regularPrice: 3300000,
    salePrice: 0,
    ingredient: '100% Yến sào (trắng)',
    mass: '100g',
    uses: 'Tổ yến chứa tới 18 loại acid amin mà cơ thể không tự tổng hợp được, cùng rất nhiều cacbonhydrat, muối khoáng, khoáng chất vi lượng.... giúp cơ thể khỏe mạnh, trẻ hóa tế bào, da trắng mịn, hồng hào và cải thiện trí nhớ.',
    preservation: 'Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp',
    expiryDate: '02 năm kể từ ngày sản xuất',
    origin: 'Việt Nam',
    currency: 'VND',
    ownerId: '619f7ec78a3dec0df2362c8f'
  },
  {
    name: 'HH12 - Yến sào thành phẩm xếp hoa hồng 50g',
    categoryId: '619f7d7c07a967f6eda06295',
    featuredImage: '/images/products/4.jpg',
    description: 'Được làm từ yến nguyên tổ mới khai thác được đem trực tiếp đến phòng sơ chế. Tổ yến sẽ được sơ chế rửa bằng nước sạch được lọc qua hệ thống RO, loại bỏ sạch hoàn toàn lông và bụi bẩn hoàn toàn thủ công, sấy khô có hình dạng xếp sợi theo định hình hoa hồng, cánh hoa hồng có nhiều sợi yến dài đắp bên ngoài bề mặt.',
    maxQuantity: 100,
    ratingAvg: 0,
    totalRatings: 0,
    regularPrice: 1650000,
    salePrice: 0,
    ingredient: '100% Yến sào (trắng)',
    mass: '100g',
    uses: 'Tổ yến chứa tới 18 loại acid amin mà cơ thể không tự tổng hợp được, cùng rất nhiều cacbonhydrat, muối khoáng, khoáng chất vi lượng.... giúp cơ thể khỏe mạnh, trẻ hóa tế bào, da trắng mịn, hồng hào và cải thiện trí nhớ.',
    preservation: 'Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp',
    expiryDate: '02 năm kể từ ngày sản xuất',
    origin: 'Việt Nam',
    currency: 'VND',
    ownerId: '619f7ec78a3dec0df2362c8f'
  },
  {
    name: 'HH13 - Yến sào thành phẩm xếp hoa hồng 10g',
    categoryId: '619f7d7c07a967f6eda06295',
    featuredImage: '/images/products/5.jpg',
    description: 'Được làm từ yến nguyên tổ mới khai thác được đem trực tiếp đến phòng sơ chế. Tổ yến sẽ được sơ chế rửa bằng nước sạch được lọc qua hệ thống RO, loại bỏ sạch hoàn toàn lông và bụi bẩn hoàn toàn thủ công, sấy khô có hình dạng xếp sợi theo định hình hoa hồng, cánh hoa hồng có nhiều sợi yến dài đắp bên ngoài bề mặt.',
    maxQuantity: 100,
    ratingAvg: 0,
    totalRatings: 0,
    regularPrice: 340000,
    salePrice: 0,
    ingredient: '100% Yến sào (trắng)',
    mass: '10g',
    uses: 'Tổ yến chứa tới 18 loại acid amin mà cơ thể không tự tổng hợp được, cùng rất nhiều cacbonhydrat, muối khoáng, khoáng chất vi lượng.... giúp cơ thể khỏe mạnh, trẻ hóa tế bào, da trắng mịn, hồng hào và cải thiện trí nhớ.',
    preservation: 'Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp',
    expiryDate: '02 năm kể từ ngày sản xuất',
    origin: 'Việt Nam',
    currency: 'VND',
    ownerId: '619f7ec78a3dec0df2362c8f'
  },
  {
    name: 'XT21 - Yến sào thành phẩm xếp tổ (Thường) 100g',
    categoryId: '619f7d7c07a967f6eda06295',
    featuredImage: '/images/products/6.jpg',
    description: 'Được làm từ yến nguyên tổ mới khai thác được đem trực tiếp đến phòng sơ chế. Tổ yến sẽ được sơ chế rửa bằng nước sạch được lọc qua hệ thống RO, loại bỏ sạch hoàn toàn lông và bụi bẩn hoàn toàn thủ công, sấy khô có hình dạng xếp sợi theo định hình hoa hồng, cánh hoa hồng có nhiều sợi yến dài đắp bên ngoài bề mặt.',
    maxQuantity: 100,
    ratingAvg: 0,
    totalRatings: 0,
    regularPrice: 3300000,
    salePrice: 0,
    ingredient: '100% Yến sào (trắng)',
    mass: '100g',
    uses: 'Tổ yến chứa tới 18 loại acid amin mà cơ thể không tự tổng hợp được, cùng rất nhiều cacbonhydrat, muối khoáng, khoáng chất vi lượng.... giúp cơ thể khỏe mạnh, trẻ hóa tế bào, da trắng mịn, hồng hào và cải thiện trí nhớ.',
    preservation: 'Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp',
    expiryDate: '02 năm kể từ ngày sản xuất',
    origin: 'Việt Nam',
    currency: 'VND',
    ownerId: '619f7ec78a3dec0df2362c8f'
  },
  {
    name: 'XT22 - Yến sào thành phẩm xếp tổ (Thường) 50g',
    categoryId: '619f7d7c07a967f6eda06295',
    featuredImage: '/images/products/7.jpg',
    description: 'Được làm từ yến nguyên tổ mới khai thác được đem trực tiếp đến phòng sơ chế. Tổ yến sẽ được sơ chế rửa bằng nước sạch được lọc qua hệ thống RO, loại bỏ sạch hoàn toàn lông và bụi bẩn hoàn toàn thủ công, sấy khô có hình dạng xếp sợi theo định hình hoa hồng, cánh hoa hồng có nhiều sợi yến dài đắp bên ngoài bề mặt.',
    maxQuantity: 100,
    ratingAvg: 0,
    totalRatings: 0,
    regularPrice: 1650000,
    salePrice: 0,
    ingredient: '100% Yến sào (trắng)',
    mass: '50g',
    uses: 'Tổ yến chứa tới 18 loại acid amin mà cơ thể không tự tổng hợp được, cùng rất nhiều cacbonhydrat, muối khoáng, khoáng chất vi lượng.... giúp cơ thể khỏe mạnh, trẻ hóa tế bào, da trắng mịn, hồng hào và cải thiện trí nhớ.',
    preservation: 'Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp',
    expiryDate: '02 năm kể từ ngày sản xuất',
    origin: 'Việt Nam',
    currency: 'VND',
    ownerId: '619f7ec78a3dec0df2362c8f'
  },
  {
    name: 'XT23 - Yến sào thành phẩm xếp tổ (Thường) 10g',
    categoryId: '619f7d7c07a967f6eda06295',
    featuredImage: '/images/products/8.jpg',
    description: 'Được làm từ yến nguyên tổ mới khai thác được đem trực tiếp đến phòng sơ chế. Tổ yến sẽ được sơ chế rửa bằng nước sạch được lọc qua hệ thống RO, loại bỏ sạch hoàn toàn lông và bụi bẩn hoàn toàn thủ công, sấy khô có hình dạng xếp sợi theo định hình hoa hồng, cánh hoa hồng có nhiều sợi yến dài đắp bên ngoài bề mặt.',
    maxQuantity: 100,
    ratingAvg: 0,
    totalRatings: 0,
    regularPrice: 340000,
    salePrice: 0,
    ingredient: '100% Yến sào (trắng)',
    mass: '10g',
    uses: 'Tổ yến chứa tới 18 loại acid amin mà cơ thể không tự tổng hợp được, cùng rất nhiều cacbonhydrat, muối khoáng, khoáng chất vi lượng.... giúp cơ thể khỏe mạnh, trẻ hóa tế bào, da trắng mịn, hồng hào và cải thiện trí nhớ.',
    preservation: 'Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp',
    expiryDate: '02 năm kể từ ngày sản xuất',
    origin: 'Việt Nam',
    currency: 'VND',
    ownerId: '619f7ec78a3dec0df2362c8f'
  },
  {
    name: 'XT11 - Yến sào thành phẩm xếp tổ (Đặc biệt) 100g',
    categoryId: '619f7d7c07a967f6eda06295',
    featuredImage: '/images/products/9.jpg',
    description: 'Được làm từ yến nguyên tổ mới khai thác được đem trực tiếp đến phòng sơ chế. Tổ yến sẽ được sơ chế rửa bằng nước sạch được lọc qua hệ thống RO, loại bỏ sạch hoàn toàn lông và bụi bẩn hoàn toàn thủ công, sấy khô có hình dạng xếp sợi theo định hình hoa hồng, cánh hoa hồng có nhiều sợi yến dài đắp bên ngoài bề mặt.',
    maxQuantity: 100,
    ratingAvg: 0,
    totalRatings: 0,
    regularPrice: 3600000,
    salePrice: 0,
    ingredient: '100% Yến sào (trắng)',
    mass: '100g',
    uses: 'Tổ yến chứa tới 18 loại acid amin mà cơ thể không tự tổng hợp được, cùng rất nhiều cacbonhydrat, muối khoáng, khoáng chất vi lượng.... giúp cơ thể khỏe mạnh, trẻ hóa tế bào, da trắng mịn, hồng hào và cải thiện trí nhớ.',
    preservation: 'Trong hộp kín, nơi khô ráo, tránh ánh nắng trực tiếp',
    expiryDate: '02 năm kể từ ngày sản xuất',
    origin: 'Việt Nam',
    currency: 'VND',
    ownerId: '619f7ec78a3dec0df2362c8f'
  }
]

module.exports = {
  PRODUCTS
}
